on: 
  issue_comment: [created]

jobs:
  command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: setup.sh
      - uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: require("./command")(github, context)
