name: comment hello

on: issue_comment

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        if: ${{ github.event.comment.body }} == "hello"
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Hello!'
            })
